services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: school-foundation-frontend

    ports:
      - "4200:80"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    restart: unless-stopped
